### ISSUE TITLE
support remote schemas

### ISSUE THREAD

**Issue by dwelch2344** [bencebalogh/avro-schema-registry#5]
Hey there, came across your library today and it's great. Does about 99% of what we need. The only thing we can't seem to do is lookup a schema from a registry directly – meaning we'd need _a priori_ knowledge of the schema in our codebase. 

We'd much rather just pull it from Schema Registry, but don't want to rewrite the code given you've done most of it already. Would you be interested in a PR to make fetching / using pre-defined schemas easier?

One option would be to change the `schema` arg in `encodeFunction(topic, schema, msg)` to support IDs of a remote schema, and pull the schema at that point. This would preserve backwards compatibility and probably be useful to most people. 

Another option would be to support searching implicitly. I'll work on some examples, but figured I'd ask here first for discussion

**Comment by dwelch2344** [comment]
Also, I should have lead with this: THANK YOU for a great lib and going open source with it :)

**Comment by bencebalogh** [comment]
I think to keep the functions' purpose cleaner it'd be better to have a separate `search` or `retrieveSchema` function and with the result of that you could call `encodeFunction`, it'd only mean one extra network call after the process has started to retrieve the schema and handling errors are cleaner too because then `encodeFunction` won't return a "schema not found" error as it's either already in the registry and the post returns the id or it'll put it there.

The reason why I thought you have the prior knowledge of the schema (having the schema in your codebase) is because the producers' logic have to know that in order to construct a correct message object and if you keep the schema in your codebase then it's easily version controlled with the logic itself.

Thanks for the kind words, if you've got a PR that's welcome, if not I'll check this over the weekend.

**Comment by loganbfisher** [comment]
I second this.  It works great man!  I was able to get it working in like 5 mins.  But we use a distributed system and having to manage these schemas in each micro service and also in a canonical schema repo is going to be a nightmare for us.  I will take a look at your code and see if I can put a PR up for it today.  Good work!

**Comment by bencebalogh** [comment]
out in `1.2.0`
